tasks:
  - name: Setup MySQL
    init: |
      Sudo apt-get update
      Sudo apt-get install -y mysql-server mysql-client
      Sudo mkdir -p /workspace/mysql-data /workspace/mysql-logs
      Sudo mysql-safe --datadir=/workspace/mysql-data\
                     --log-error=/workspace/mysql-logs/error.log \
                     --pid-file=/workspace/mysql-logs/mysql.pid \
                     --skip-grant-tabeles \
                     --skip-networking=0 \
                     --bind-address=0.0.0.0 &
    command: |
      echo "MySQL está rodando"
      mysql --version

ports:
  - port: 3306
    onOpen: ignore 



